routes/web.php
        Route::post('update-profile', 'VenderController@editprofile')->name('update.profile')->middleware(
            [
                'auth:vender',
                'XSS','revalidate',
            ]
        );
        Route::post('billing-info', 'VenderController@editBilling')->name('update.billing.info')->middleware(
            [
                'auth:vender',
                'XSS','revalidate',
            ]
        );
        Route::post('shipping-info', 'VenderController@editShipping')->name('update.shipping.info')->middleware(
            [
                'auth:vender',
                'XSS','revalidate',
            ]
        );
        Route::post('change.password', 'VenderController@updatePassword')->name('update.password')->middleware(
            [
                'auth:vender',
                'XSS','revalidate',
            ]
        );
        Route::get('change-language/{lang}', 'VenderController@changeLanquage')->name('change.language')->middleware(
            [
                'auth:vender',
                'XSS','revalidate',
            ]
        );

    }
);


Route::get('/', 'DashboardController@index')->name('dashboard')->middleware(['XSS','revalidate',]);

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);
Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);
Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);
Route::get('profile', 'UserController@profile')->name('profile')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);
Route::post('edit-profile', 'UserController@editprofile')->name('update.account')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);

Route::resource('users', 'UserController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);
Route::post('change-password', 'UserController@updatePassword')->name('update.password');


Route::resource('roles', 'RoleController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);
Route::resource('permissions', 'PermissionController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){
    Route::get('change-language/{lang}', 'LanguageController@changeLanquage')->name('change.language');
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language');
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data');
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language');
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language');

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy');
}
);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){

    Route::resource('systems', 'SystemController');
    Route::post('email-settings', 'SystemController@saveEmailSettings')->name('email.settings');
    Route::post('company-settings', 'SystemController@saveCompanySettings')->name('company.settings');
    Route::post('stripe-settings', 'SystemController@savePaymentSettings')->name('payment.settings');
    Route::post('system-settings', 'SystemController@saveSystemSettings')->name('system.settings');
    Route::get('company-setting', 'SystemController@companyIndex')->name('company.setting');
    Route::post('business-setting', 'SystemController@saveBusinessSettings')->name('business.setting');
    Route::post('company-payment-setting', 'SystemController@saveCompanyPaymentSettings')->name('company.payment.settings');
    Route::get('test-mail', 'SystemController@testMail')->name('test.mail');
    Route::post('test-mail', 'SystemController@testSendMail')->name('test.send.mail');

}
);


Route::get('productservice/index', 'ProductServiceController@index')->name('productservice.index');
Route::resource('productservice', 'ProductServiceController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);


Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){

    Route::get('customer/{id}/show', 'CustomerController@show')->name('customer.show');
    Route::resource('customer', 'CustomerController');

}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){

    Route::get('vender/{id}/show', 'VenderController@show')->name('vender.show');
    Route::resource('vender', 'VenderController');

}
);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){

    Route::resource('bank-account', 'BankAccountController');

}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){

    Route::get('transfer/index', 'TransferController@index')->name('transfer.index');
    Route::resource('transfer', 'TransferController');

}
);


Route::resource('taxes', 'TaxController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);

Route::resource('product-category', 'ProductServiceCategoryController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);

Route::resource('product-unit', 'ProductServiceUnitController')->middleware(
    [
        'auth',
        'XSS','revalidate',
    ]
);


Route::get('invoice/print/{id}', 'InvoiceController@print')->name('invoice.print')->middleware(['XSS','revalidate',]);
Route::get('invoice/pdf/{id}', 'InvoiceController@invoice')->name('invoice.pdf')->middleware(['XSS','revalidate',]);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){


    Route::get('invoice/{id}/duplicate', 'InvoiceController@duplicate')->name('invoice.duplicate');
    Route::get('invoice/{id}/shipping/print', 'InvoiceController@shippingDisplay')->name('invoice.shipping.print');
    Route::get('invoice/{id}/payment/reminder', 'InvoiceController@paymentReminder')->name('invoice.payment.reminder');
    Route::get('invoice/index', 'InvoiceController@index')->name('invoice.index');
    Route::post('invoice/product/destroy', 'InvoiceController@productDestroy')->name('invoice.product.destroy');
    Route::post('invoice/product', 'InvoiceController@product')->name('invoice.product');
    Route::post('invoice/customer', 'InvoiceController@customer')->name('invoice.customer');
    Route::get('invoice/{id}/sent', 'InvoiceController@sent')->name('invoice.sent');
    Route::get('invoice/{id}/resent', 'InvoiceController@resent')->name('invoice.resent');
    Route::get('invoice/{id}/payment', 'InvoiceController@payment')->name('invoice.payment');
    Route::post('invoice/{id}/payment', 'InvoiceController@createPayment')->name('invoice.payment');
    Route::post('invoice/{id}/payment/{pid}/destroy', 'InvoiceController@paymentDestroy')->name('invoice.payment.destroy');
    Route::get('invoice/items', 'InvoiceController@items')->name('invoice.items');

    Route::resource('invoice', 'InvoiceController');
    Route::get('invoice/create/{cid}', 'InvoiceController@create')->name('invoice.create');
}
);

Route::get(
    '/invoices/preview/{template}/{color}', [
                                              'as' => 'invoice.preview',
                                              'uses' => 'InvoiceController@previewInvoice',
                                          ]
);
Route::post(
    '/invoices/template/setting', [
                                    'as' => 'template.setting',
                                    'uses' => 'InvoiceController@saveTemplateSettings',
                                ]
);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){


    Route::get('credit-note', 'CreditNoteController@index')->name('credit.note');
    Route::get('custom-credit-note', 'CreditNoteController@customCreate')->name('invoice.custom.credit.note');
    Route::post('custom-credit-note', 'CreditNoteController@customStore')->name('invoice.custom.credit.note');
    Route::get('credit-note/invoice', 'CreditNoteController@getinvoice')->name('invoice.get');
    Route::get('invoice/{id}/credit-note', 'CreditNoteController@create')->name('invoice.credit.note');
    Route::post('invoice/{id}/credit-note', 'CreditNoteController@store')->name('invoice.credit.note');
    Route::get('invoice/{id}/credit-note/edit/{cn_id}', 'CreditNoteController@edit')->name('invoice.edit.credit.note');
    Route::post('invoice/{id}/credit-note/edit/{cn_id}', 'CreditNoteController@update')->name('invoice.edit.credit.note');
    Route::delete('invoice/{id}/credit-note/delete/{cn_id}', 'CreditNoteController@destroy')->name('invoice.delete.credit.note');

}
);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS','revalidate',
        ],
    ], function (){


    Route::get('debit-note', 'DebitNoteController@index')->name('debit.note');
    Route::get('custom-debit-note', 'DebitNoteController@customCreate')->name('bill.custom.debit.note');
    Route::post('custom-debit-note', 'DebitNoteController@customStore')->name('bill.custom.debit.note');
    Route::get('debit-note/bill', 'DebitNoteController@getbill')->name('bill.get');
    Route::get('bill/{id}/debit-note', 'DebitNoteController@create')->name('bill.debit.note');

resources/views/settings/create.blade.php
@extends('layouts.main')
@section('content')
<section class="section">
    <div class="section-header">
        <h1 class="d-inline">{{__('Role')}} </h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4>{{__('Create Role')}} </h4>
                </div>
                {{Form::open(array('url'=>'roles','method'=>'post'))}}
                    <div class="card-body">
                        <div class="form-group">
                            {{Form::label('name',__('Name'))}}
                            {{Form::text('name',null,array('class'=>'form-control','placeholder'=>__('Enter Role Name')))}}
                            @error('name')
                            <span class="invalid-name" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            @if(!empty($permissions))
                                <h6>{{__('Assign Permission to Roles')}} </h6>
                                <table class="table table-striped mb-0" id="dataTable-1">
                                <thead>
                                <tr>
                                    <th>{{__('Module')}} </th>
                                    <th>{{__('Permissions')}} </th>
                                </tr>
                                </thead>
                                <tbody>
                                @php
                                    $modules=['user','language','account'];
                                @endphp
                                @foreach($modules as $module)
                                    <tr>
                                        <td>{{ ucfirst($module) }}</td>
                                        <td>
                                            @if(in_array('manage '.$module,(array) $permissions))
                                                @if($key = array_search('manage '.$module,$permissions))
                                                    <div class="form-check form-check-inline">
                                                        {{Form::checkbox('permissions[]',$key,false, ['id' =>'permission'.$key])}}
                                                        {{Form::label('permission'.$key,'Manage')}}<br>
                                                    </div>
                                                @endif
                                            @endif
                                            @if(in_array('create '.$module,(array) $permissions))
                                                @if($key = array_search('create '.$module,$permissions))
                                                    <div class="form-check form-check-inline">
                                                        {{Form::checkbox('permissions[]',$key,false, ['id' =>'permission'.$key])}}
                                                        {{Form::label('permission'.$key,'Create')}}<br>
                                                    </div>
                                                @endif
                                            @endif
                                            @if(in_array('edit '.$module,(array) $permissions))
                                                @if($key = array_search('edit '.$module,$permissions))
                                                    <div class="form-check form-check-inline">
                                                        {{Form::checkbox('permissions[]',$key,false, ['id' =>'permission'.$key])}}
                                                        {{Form::label('permission'.$key,'Edit')}}<br>
                                                    </div>
                                                @endif
                                            @endif
                                            @if(in_array('delete '.$module,(array) $permissions))
                                                @if($key = array_search('delete '.$module,$permissions))
                                                    <div class="form-check form-check-inline">
                                                        {{Form::checkbox('permissions[]',$key,false, ['id' =>'permission'.$key])}}
                                                        {{Form::label('permission'.$key,'Delete')}}<br>
                                                    </div>
                                                @endif
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                             @endif
                        </div>
                    </div>
                    <div class="card-footer">
                        {{Form::submit(__('Create'),array('class'=>'btn btn-primary'))}}
                        <a href="{{ route('roles.index') }}" class="btn btn-danger" >{{__('Cancel')}}</a>
                    </div>
                {{Form::close()}}
            </div>
        </div>
    </div>
</section>
@endsection
<script>

</script>

resources/views/settings/edit.blade.php
@extends('layouts.main')
@section('content')
    <section class="section">
        <div class="section-header">
            <h1 class="d-inline">{{__('Role')}} </h1>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>{{__('Update Role')}} </h4>
                    </div>

                    {{Form::model($role,array('route' => array('roles.update', $role->id), 'method' => 'PUT')) }}
                    <div class="card-body">
                        <div class="form-group">
                            {{Form::label('name',__('Name'))}}
                            {{Form::text('name',null,array('class'=>'form-control'))}}
                            @error('name')
                            <span class="invalid-name" role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                        </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            @if(!empty($permissions))
                                <h6>{{__('Assign Permission to Roles')}} </h6>
                                <table class="table table-striped mb-0" id="dataTable-1">
                                    <thead>
                                    <tr>
                                        <th>{{__('Module')}} </th>
                                        <th>{{__('Permissions')}} </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @php
                                        $modules=['user','language','account'];
                                    @endphp
                                    @foreach($modules as $module)
                                        <tr>
                                            <td>{{ ucfirst($module) }}</td>
                                            <td>
                                                @if(in_array('manage '.$module,(array) $permissions))
                                                    @if($key = array_search('manage '.$module,$permissions))
                                                        <div class="form-check form-check-inline">
                                                            {{Form::checkbox('permissions[]',$key,$role->permission, ['id' =>'permission'.$key])}}
                                                            {{Form::label('permission'.$key,'Manage')}}<br>
                                                        </div>
                                                    @endif
                                                @endif
                                                @if(in_array('create '.$module,(array) $permissions))
                                                    @if($key = array_search('create '.$module,$permissions))
                                                        <div class="form-check form-check-inline">
                                                            {{Form::checkbox('permissions[]',$key,$role->permission, ['id' =>'permission'.$key])}}
                                                            {{Form::label('permission'.$key,'Create')}}<br>
                                                        </div>
                                                    @endif
                                                @endif
                                                @if(in_array('edit '.$module,(array) $permissions))
                                                    @if($key = array_search('edit '.$module,$permissions))
                                                        <div class="form-check form-check-inline">
                                                            {{Form::checkbox('permissions[]',$key,$role->permission, ['id' =>'permission'.$key])}}
                                                            {{Form::label('permission'.$key,'Edit')}}<br>
                                                        </div>
                                                    @endif
                                                @endif
                                                @if(in_array('delete '.$module,(array) $permissions))
                                                    @if($key = array_search('delete '.$module,$permissions))
                                                        <div class="form-check form-check-inline">
                                                            {{Form::checkbox('permissions[]',$key,$role->permission, ['id' =>'permission'.$key])}}
                                                            {{Form::label('permission'.$key,'Delete')}}<br>
                                                        </div>
                                                    @endif
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @endif
                            @error('permissions')
                            <span class="invalid-permissions" role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                        </span>
                            @enderror
                        </div>
                    </div>
                    <div class="card-footer">
                        {{Form::submit(__('Update'),array('class'=>'btn btn-primary'))}}
                        <a href="{{ route('roles.index') }}" class="btn btn-danger">{{__('Cancel')}} </a>
                    </div>
                    {{Form::close()}}

                </div>
            </div>
        </div>
    </section>
@endsection
<script>

</script>

resources/views/settings/test_mail.blade.php
<div class="card bg-none card-box">
    {{ Form::open(array('route' => array('test.send.mail'))) }}
    <div class="row">
        <div class="form-group col-md-12">
            {{ Form::label('email', __('Email')) }}
            {{ Form::text('email', '', array('class' => 'form-control','required'=>'required')) }}
            @error('email')
            <span class="invalid-email" role="alert">
            <strong class="text-danger">{{ $message }}</strong>
        </span>
            @enderror
        </div>
    </div>
    <div class="col-md-12">
        <input type="submit" value="{{__('Create')}}" class="btn-create badge-blue">
        <input type="button" value="{{__('Cancel')}}" class="btn-create bg-gray" data-dismiss="modal">
    </div>
    {{ Form::close() }}
</div>